import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import NavbarMegaMenu from "../components/NavbarMegaMenu/NavbarMegaMenu";
import { Slider } from "../components/Slider/Slider";
import SocialMedia from "../components/SocialMedia/SocialMedia";
import SectionAbout from "../components/SectionAbout/SectionAbout";
import { SliderAbout } from "../components/SectionAbout/SliderAbout";
// import CountdownTimer from "../components/CountdownTimer/CountdownTimer";
// import SectionCourses from "../components/SectionCourses/SectionCourses";
// import StockQuotes from "../components/StockQuotes/StockQuotes";
// import BooksCollection from "../components/BooksCollection/BooksCollection";
// import Newsletter from "../components/Newsletter/Newsletter";

import { Loading } from "../components/Loading/Loading";
import AboutMe from "../components/AboutMe/AboutMe";

export default function Home() {
  const [loading, setLoading] = useState(true);
  // Discount Countdown
  // const THREE_DAYS_IN_MS = 3 * 24 * 60 * 60 * 1000;
  // const NOW_IN_MS = new Date().getTime();
  // const dateTimeAfterThreeDays = NOW_IN_MS + THREE_DAYS_IN_MS;

  if (loading) {
    setTimeout(() => {
      setLoading(false);
    }, 1000);
  }

  return loading ? (
    <Loading />
  ) : (
    // return (
    <div className="container">
      <Head>
        <title>Stocks Force One</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <NavbarMegaMenu />
        {/* Discount banner */}
        {/* <div className="discount">
          <h3 className="discount-text">
            10% Discount on All Courses{" "}
            <CountdownTimer targetDate={dateTimeAfterThreeDays} />
          </h3>
        </div> */}
        {/* Video Slider Hero */}
        <div className="hero-area">
          <Slider autoplayInterval={6000} />
        </div>
        <span className="line-background line-bg-1"></span>
        <span className="line-background line-bg-2"></span>
        <span className="line-background line-bg-3"></span>
        <span className="line-background line-bg-4"></span>
        <span className="line-background line-bg-5"></span>
        <span className="line-background line-bg-6"></span>
        <span className="line-background line-bg-7"></span>

        <SectionAbout />
        <SliderAbout autoplayInterval={6000} />
        <AboutMe />

        <SocialMedia />
      </main>
    </div>
  );
}
