import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import NavbarMegaMenu from "../components/NavbarMegaMenu/NavbarMegaMenu";
import CountdownTimer from "../components/CountdownTimer/CountdownTimer";
import { Slider } from "../components/Slider/Slider";
import SectionCourses from "../components/SectionCourses/SectionCourses";
import CircleProgress from "../components/CircleProgress/CircleProgress";
import Circle from "../components/CircleProgress/Circle";
import StockQuotes from "../components/StockQuotes/StockQuotes";

export default function Home() {
  const THREE_DAYS_IN_MS = 3 * 24 * 60 * 60 * 1000;
  const NOW_IN_MS = new Date().getTime();

  const dateTimeAfterThreeDays = NOW_IN_MS + THREE_DAYS_IN_MS;

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <NavbarMegaMenu />
        {/* Discount banner */}
        <div className="discount">
          <h3 className="discount-text">
            10% Discount on All Courses{" "}
            <CountdownTimer targetDate={dateTimeAfterThreeDays} />
          </h3>
        </div>
        {/* Video Slider Hero */}
        <div className="hero-area">
          <Slider autoplayInterval={6000} />
        </div>
        {/* Hard coded Section Hero */}
        {/* <section className="hero-video-area">
          <div className="text-bg">
            <span className="bg-patrat"></span>
            <div className="text">
              <h1 className="title">Dan Toma</h1>
              <span className="line"></span>
              <p className="description">
                Imprimeur anonyme assembla ensemble des morceaux de texte pour
                réaliser un livre spécimen de polices de texte. Il n’a pas fait
                que survivre cinq siècles, mais s’est aussi adapt à la
                bureautique informatique, sans que son contenu n’en soit
                modifié.
              </p>
            </div>
          </div>
          <span className="video-filter"></span>
          <div className="video-wrapper">
            <video
              className="video"
              autoPlay={"autoplay"}
              preload="auto"
              muted
              loop
            >
              <source src="/video/video.mp4" type="video/mp4" />
            </video>
          </div>
        </section> */}
        {/* Quotes Stocks */}
        <StockQuotes />
        <SectionCourses />
      </main>
    </div>
  );
}
